const fs = require('fs');
let code = fs.readFileSync('ui.js', 'utf8');
code += `\n\n// --- BOTTOM NAV SCROLL BEHAVIOR ---\n`;
code += `document.addEventListener('DOMContentLoaded', () => {\n`;
code += `    let isCompact = false;\n`;
code += `    \n`;
code += `    window.addEventListener('scroll', () => {\n`;
code += `        const nav = document.querySelector('.bottom-nav');\n`;
code += `        if (!nav) return;\n`;
code += `        \n`;
code += `        const currentScrollY = window.scrollY || document.documentElement.scrollTop;\n`;
code += `        \n`;
code += `        if (currentScrollY > 50 && !isCompact) {\n`;
code += `            isCompact = true;\n`;
code += `            nav.classList.add('compact');\n`;
code += `        } else if (currentScrollY <= 10 && isCompact) {\n`;
code += `            isCompact = false;\n`;
code += `            nav.classList.remove('compact');\n`;
code += `        }\n`;
code += `    }, { passive: true });\n`;
code += `    \n`;
code += `    setTimeout(() => {\n`;
code += `        const nav = document.querySelector('.bottom-nav');\n`;
code += `        const currentScrollY = window.scrollY || document.documentElement.scrollTop;\n`;
code += `        if (nav && currentScrollY > 50) {\n`;
code += `            isCompact = true;\n`;
code += `            nav.classList.add('compact');\n`;
code += `        }\n`;
code += `    }, 100);\n`;
code += `});\n`;
fs.writeFileSync('ui.js', code);
